# Generated by Django 3.2.5 on 2021-08-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='Blog/images')),
                ('puplishde_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(max_length=5000)),
                ('owner', models.CharField(max_length=100)),
                ('About_blog_By_owner', models.TextField(max_length=100)),
                ('instagram_feed', models.URLField(max_length=100)),
            ],
        ),
    ]
