# Generated by Django 3.2.5 on 2021-08-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_about_blog_by_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='owner_image',
            field=models.ImageField(default='', upload_to='Blog/images/owners'),
            preserve_default=False,
        ),
    ]
