# Generated by Django 3.2.5 on 2021-09-04 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_blog_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='owner',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
