# Generated by Django 3.2.5 on 2021-09-04 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_blog_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='owner_image',
            field=models.ImageField(blank=True, null=True, upload_to='Blog/images/owners'),
        ),
    ]
