# Generated by Django 3.2.5 on 2021-09-04 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_blog_owner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='About_blog_By_owner',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
