# Generated by Django 3.2.5 on 2021-08-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(default='', upload_to='testimonial/images'),
            preserve_default=False,
        ),
    ]
