# Generated by Django 3.2.5 on 2021-09-04 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210827_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='apout',
            field=models.TextField(default='hi'),
        ),
    ]
