# Generated by Django 3.2.5 on 2021-08-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_auto_20210823_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='j',
            field=models.ManyToManyField(related_name='jobs', to='job.Job'),
        ),
    ]
