# Generated by Django 3.2.5 on 2021-08-23 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_category_j'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='j',
            new_name='jobs',
        ),
    ]
