# Generated by Django 3.2.5 on 2021-08-27 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0016_job_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='jobs',
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='job.category'),
        ),
    ]
