# Generated by Django 3.2.5 on 2021-08-27 13:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0018_auto_20210827_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='like',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
